name: Run Overpass to GeoJSON Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: List directory contents before run
      run: ls -la
    
    - name: Display Python script content
      run: cat overpass-extract.py
    
    - name: Run Python script
      run: python overpass-extract.py
      continue-on-error: true
    
    - name: List directory contents after run
      run: ls -la
    
    - name: Check if output file exists
      run: |
        if [ -f buildings.geojson ]; then
          echo "buildings.geojson exists."
          head -n 20 buildings.geojson
        else
          echo "buildings.geojson does not exist."
        fi
    
    - name: Upload GeoJSON output
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: output-geojson
        path: |
          buildings.geojson
          *.log
        if-no-files-found: warn
